package model;
// Generated 08-mar-2022 19:53:27 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int codClient;
     private String clientName;
     private String clientSurname;
     private String clientNif;
     private String clientAddress;
     private String telephoneNum;
     private int codLawyer;

    public Client() {
    }

	
    public Client(int codClient, String clientName, String telephoneNum, int codLawyer) {
        this.codClient = codClient;
        this.clientName = clientName;
        this.telephoneNum = telephoneNum;
        this.codLawyer = codLawyer;
    }
    public Client(int codClient, String clientName, String clientSurname, String clientNif, String clientAddress, String telephoneNum, int codLawyer) {
       this.codClient = codClient;
       this.clientName = clientName;
       this.clientSurname = clientSurname;
       this.clientNif = clientNif;
       this.clientAddress = clientAddress;
       this.telephoneNum = telephoneNum;
       this.codLawyer = codLawyer;
    }
   
    public int getCodClient() {
        return this.codClient;
    }
    
    public void setCodClient(int codClient) {
        this.codClient = codClient;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getClientSurname() {
        return this.clientSurname;
    }
    
    public void setClientSurname(String clientSurname) {
        this.clientSurname = clientSurname;
    }
    public String getClientNif() {
        return this.clientNif;
    }
    
    public void setClientNif(String clientNif) {
        this.clientNif = clientNif;
    }
    public String getClientAddress() {
        return this.clientAddress;
    }
    
    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress;
    }
    public String getTelephoneNum() {
        return this.telephoneNum;
    }
    
    public void setTelephoneNum(String telephoneNum) {
        this.telephoneNum = telephoneNum;
    }
    public int getCodLawyer() {
        return this.codLawyer;
    }
    
    public void setCodLawyer(int codLawyer) {
        this.codLawyer = codLawyer;
    }




}


