package model;
// Generated 08-mar-2022 19:53:27 by Hibernate Tools 4.3.1



/**
 * Entity generated by hbm2java
 */
public class Entity  implements java.io.Serializable {


     private int codEntity;
     private String entityName;
     private String entityAddress;
     private String telephoneNum;

    public Entity() {
    }

	
    public Entity(int codEntity) {
        this.codEntity = codEntity;
    }
    public Entity(int codEntity, String entityName, String entityAddress, String telephoneNum) {
       this.codEntity = codEntity;
       this.entityName = entityName;
       this.entityAddress = entityAddress;
       this.telephoneNum = telephoneNum;
    }
   
    public int getCodEntity() {
        return this.codEntity;
    }
    
    public void setCodEntity(int codEntity) {
        this.codEntity = codEntity;
    }
    public String getEntityName() {
        return this.entityName;
    }
    
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }
    public String getEntityAddress() {
        return this.entityAddress;
    }
    
    public void setEntityAddress(String entityAddress) {
        this.entityAddress = entityAddress;
    }
    public String getTelephoneNum() {
        return this.telephoneNum;
    }
    
    public void setTelephoneNum(String telephoneNum) {
        this.telephoneNum = telephoneNum;
    }




}


