package model;
// Generated 08-mar-2022 19:53:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Issue generated by hbm2java
 */
public class Issue  implements java.io.Serializable {


     private IssueId id;
     private String issueDescription;
     private Date entryDate;
     private Date endDate;
     private Integer hoursNum;
     private Integer cost;

    public Issue() {
    }

	
    public Issue(IssueId id, Date entryDate) {
        this.id = id;
        this.entryDate = entryDate;
    }
    public Issue(IssueId id, String issueDescription, Date entryDate, Date endDate, Integer hoursNum, Integer cost) {
       this.id = id;
       this.issueDescription = issueDescription;
       this.entryDate = entryDate;
       this.endDate = endDate;
       this.hoursNum = hoursNum;
       this.cost = cost;
    }
   
    public IssueId getId() {
        return this.id;
    }
    
    public void setId(IssueId id) {
        this.id = id;
    }
    public String getIssueDescription() {
        return this.issueDescription;
    }
    
    public void setIssueDescription(String issueDescription) {
        this.issueDescription = issueDescription;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Integer getHoursNum() {
        return this.hoursNum;
    }
    
    public void setHoursNum(Integer hoursNum) {
        this.hoursNum = hoursNum;
    }
    public Integer getCost() {
        return this.cost;
    }
    
    public void setCost(Integer cost) {
        this.cost = cost;
    }




}


