package model;
// Generated 08-mar-2022 19:53:27 by Hibernate Tools 4.3.1



/**
 * IssueId generated by hbm2java
 */
public class IssueId  implements java.io.Serializable {


     private int codIssue;
     private int codClient;
     private int codEntity;

    public IssueId() {
    }

    public IssueId(int codIssue, int codClient, int codEntity) {
       this.codIssue = codIssue;
       this.codClient = codClient;
       this.codEntity = codEntity;
    }
   
    public int getCodIssue() {
        return this.codIssue;
    }
    
    public void setCodIssue(int codIssue) {
        this.codIssue = codIssue;
    }
    public int getCodClient() {
        return this.codClient;
    }
    
    public void setCodClient(int codClient) {
        this.codClient = codClient;
    }
    public int getCodEntity() {
        return this.codEntity;
    }
    
    public void setCodEntity(int codEntity) {
        this.codEntity = codEntity;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IssueId) ) return false;
		 IssueId castOther = ( IssueId ) other; 
         
		 return (this.getCodIssue()==castOther.getCodIssue())
 && (this.getCodClient()==castOther.getCodClient())
 && (this.getCodEntity()==castOther.getCodEntity());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodIssue();
         result = 37 * result + this.getCodClient();
         result = 37 * result + this.getCodEntity();
         return result;
   }   


}


