package model;
// Generated 08-mar-2022 19:53:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lawyer generated by hbm2java
 */
public class Lawyer  implements java.io.Serializable {


     private int codLawyer;
     private String lawyerNif;
     private String lawyerName;
     private String lawyerSurname;
     private Short phoneExt;
     private String userName;
     private String userPassword;
     private String photo;
     private Date entryDate;
     private Integer hoursFee;

    public Lawyer() {
    }

    public Lawyer(int codLawyer, String userName, String userPassword) {
        this.codLawyer = codLawyer;
        this.userName = userName;
        this.userPassword = userPassword;
    }
    
    public Lawyer(int codLawyer, String lawyerNif, String lawyerName, String lawyerSurname, Short phoneExt, String userName, String userPassword, String photo, Date entryDate, Integer hoursFee) {
       this.codLawyer = codLawyer;
       this.lawyerNif = lawyerNif;
       this.lawyerName = lawyerName;
       this.lawyerSurname = lawyerSurname;
       this.phoneExt = phoneExt;
       this.userName = userName;
       this.userPassword = userPassword;
       this.photo = photo;
       this.entryDate = entryDate;
       this.hoursFee = hoursFee;
    }
   
    public int getCodLawyer() {
        return this.codLawyer;
    }
    
    public void setCodLawyer(int codLawyer) {
        this.codLawyer = codLawyer;
    }
    public String getLawyerNif() {
        return this.lawyerNif;
    }
    
    public void setLawyerNif(String lawyerNif) {
        this.lawyerNif = lawyerNif;
    }
    public String getLawyerName() {
        return this.lawyerName;
    }
    
    public void setLawyerName(String lawyerName) {
        this.lawyerName = lawyerName;
    }
    public String getLawyerSurname() {
        return this.lawyerSurname;
    }
    
    public void setLawyerSurname(String lawyerSurname) {
        this.lawyerSurname = lawyerSurname;
    }
    public Short getPhoneExt() {
        return this.phoneExt;
    }
    
    public void setPhoneExt(Short phoneExt) {
        this.phoneExt = phoneExt;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
    public Integer getHoursFee() {
        return this.hoursFee;
    }
    
    public void setHoursFee(Integer hoursFee) {
        this.hoursFee = hoursFee;
    }




}


